# Generated by Django 4.2 on 2023-06-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='data_day',
            field=models.CharField(choices=[('500mb-dia', '500GB'), ('2gb', '2GB'), ('1gb', '1GB'), ('ilimitado', 'Ilimitado')], max_length=15),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('RP', 'Reprocessar'), ('CC', 'Cancelado'), ('AT', 'Ativado'), ('PR', 'Processando'), ('RB', 'Reembolsado')], default='PR', max_length=2),
        ),
    ]
