# Generated by Django 4.2 on 2023-06-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_alter_orders_data_day_alter_orders_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('CC', 'Cancelado'), ('RB', 'Reembolsado'), ('PR', 'Processando'), ('RP', 'Reprocessar'), ('AT', 'Ativado')], default='PR', max_length=2),
        ),
        migrations.AlterField(
            model_name='orders',
            name='product',
            field=models.CharField(choices=[('chip-internacional-eua-e-canada', 'USA e CANADA'), ('chip-internacional-eua', 'USA'), ('chip-internacional-global', 'GLOBAL PREMIUM'), ('chip-internacional-europa', 'EUROPA')], max_length=35),
        ),
    ]
