# Generated by Django 4.2 on 2023-06-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_alter_orders_order_status_alter_orders_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='data_day',
            field=models.CharField(choices=[('500mb-dia', '500GB'), ('2gb', '2GB'), ('ilimitado', 'Ilimitado'), ('1gb', '1GB')], max_length=15),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('RB', 'Reembolsado'), ('AT', 'Ativado'), ('RP', 'Reprocessar'), ('CC', 'Cancelado'), ('PR', 'Processando')], default='PR', max_length=2),
        ),
        migrations.AlterField(
            model_name='orders',
            name='product',
            field=models.CharField(choices=[('chip-internacional-europa', 'EUROPA'), ('chip-internacional-eua', 'USA'), ('chip-internacional-global', 'GLOBAL PREMIUM'), ('chip-internacional-eua-e-canada', 'USA e CANADA')], max_length=35),
        ),
    ]
