# Generated by Django 4.2 on 2023-06-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_alter_orders_data_day_alter_orders_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='data_day',
            field=models.CharField(choices=[('500mb-dia', '500GB'), ('ilimitado', 'Ilimitado'), ('1gb', '1GB'), ('2gb', '2GB')], max_length=15),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('RB', 'Reembolsado'), ('PR', 'Processando'), ('RP', 'Reprocessar'), ('AT', 'Ativado'), ('CC', 'Cancelado')], default='PR', max_length=2),
        ),
    ]
