# Generated by Django 4.2 on 2023-06-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sims',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sim', models.CharField(max_length=20)),
                ('link', models.URLField(blank=True, null=True)),
                ('type', models.CharField(choices=[('esim', 'eSIM (Virtual)'), ('sim', 'SIM (Físico)')], max_length=4)),
                ('operator', models.CharField(choices=[('TM', 'T-Mobile'), ('TC', 'Telcom'), ('CM', 'China Mobile')], max_length=2)),
                ('sim_status', models.CharField(choices=[('CC', 'Cancelado'), ('DS', 'Disponível'), ('AT', 'Ativado')], default='DS', max_length=2)),
            ],
        ),
    ]
