# Generated by Django 4.2 on 2023-06-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0006_alter_sims_sim_status_alter_sims_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sims',
            name='operator',
            field=models.CharField(choices=[('CM', 'China Mobile'), ('TM', 'T-Mobile'), ('TC', 'Telcom')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sims',
            name='sim_status',
            field=models.CharField(choices=[('CC', 'Cancelado'), ('DS', 'Disponível'), ('AT', 'Ativado')], default='DS', max_length=2),
        ),
    ]
